spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database1
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-airbnb-clone.us.auth0.com/

auth0:
  audience: mern-food-ordering-app-api


application:
  file:
    uploads:
      path: ./uploads
cloudinary:
  cloud-name: dxhlxhjxw
  api-key: 948155626724819
  api-secret: iVmZ5QZKz4mcvh58prZzZxU2I6k

server:
  port: 7000
logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG
